use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :api, Restfid.API.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [
    scheme: System.get_env("URL_SCHEME") || "https",
    host: System.get_env("URL_HOST") || "appfid.com",
    port: String.to_integer(System.get_env("URL_PORT") || "443")
  ],
  scope_opts: [host: "api."]

# Guardian config
config :api, Restfid.API.Guardian,
  issuer: "api",
  secret_key: System.get_env("SECRET_KEY_BASE")